### ISSUE TITLE
Apparent layout change on small screens since 1.14.0

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#1215]
### Current Behavior

I am not sure if this is a regression or an intended change.  I have a page with Layout Fixed and Theme Sizings settings:

![image](https://github.com/user-attachments/assets/3e00f52a-05d7-4ac7-9967-167bafed71b4)

Using version 1.14.0 of the dashboard, in a small window, and on a tablet, with three groups each 3 wide, it looks like 

![Screenshot from 2024-08-17 08-48-51](https://github.com/user-attachments/assets/2b071b5e-029f-41c2-97cc-85ecd787a896)

but with the current `main` branch (16th Aug 2024), in the same window size, it only shows two groups across, pushing the third off the screen.

![image](https://github.com/user-attachments/assets/14934ce0-2349-4498-a8e6-cd1bc0949400)

Is this an intended change, and if it is how do I restore the previous functionality please?

### Environment

- Dashboard version: Current main branch, commit cd5d1ce42a
- Node-RED version: 4.0.2
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by joepavitt** [comment]
Hmmm, certainly not intentional - the padding/sizings look consistent, it appears the gauges themselves are rendering wider?

**Comment by colinl** [comment]
Running two instances of node-red, both with only the dashboard installed, one with 1.14.0 and one with main from github, both running only the flow below, which is three text widgets, each 3x1, in three groups of size 3x1, in a PC I see

![image](https://github.com/user-attachments/assets/1a7093e8-2c39-46fe-8a73-6f1225cec5fc)

That is both running at the same time with a page open on each in Edge browser.  It can be seen that the latest main has significantly larger groups than 1.14.0, which means they do not fit on the tablet.  There are no CSS overrides, only those three nodes and default theme.

I notice that the colour of the text has changed too, was that intentional?

```
[{"id":"cdf515413f178f83","type":"ui-text","z":"bb54aef01db48493","group":"6255fc3f7023c25f","order":1,"width":"3","height":"1","name":"text 1","label":"text 1","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":470,"y":260,"wires":[]},{"id":"78c35eff33a58ee3","type":"ui-text","z":"bb54aef01db48493","group":"4d52b7074513b4cf","order":1,"width":"3","height":"1","name":"text 2","label":"text 2","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":470,"y":320,"wires":[]},{"id":"a7be58d828009851","type":"ui-text","z":"bb54aef01db48493","group":"902105b55c678f0e","order":1,"width":"3","height":"1","name":"text 3","label":"text 3","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":470,"y":380,"wires":[]},{"id":"6255fc3f7023c25f","type":"ui-group","name":"Three groups test 1","page":"e499766061486e72","width":"3","height":"1","order":1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"4d52b7074513b4cf","type":"ui-group","name":"Three groups test 2","page":"e499766061486e72","width":"3","height":"1","order":2,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"902105b55c678f0e","type":"ui-group","name":"Three groups test 3","page":"e499766061486e72","width":"3","height":"1","order":3,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"e499766061486e72","type":"ui-page","name":"Three groups test 1.14.0","ui":"ID-BASE-1","path":"/page11","icon":"home","layout":"flex","theme":"a965ccfef139317a","order":1,"className":"","visible":"true","disabled":"false"},{"id":"ID-BASE-1","type":"ui-base","name":"Dashboard","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-control","ui-notification","ui-gauge-classic"]},{"id":"a965ccfef139317a","type":"ui-theme","name":"Default","colors":{"surface":"#404040","primary":"#109fbc","bgPage":"#e8e8e8","groupBg":"#d6d6d6","groupOutline":"#6fbc10"},"sizes":{"pagePadding":"12px","groupGap":"12px","groupBorderRadius":"4px","widgetGap":"12px"}}]
```

**Comment by joepavitt** [comment]
> I notice that the colour of the text has changed too, was that intentional?

Not that I can recall - this will need some investigating

**Comment by joepavitt** [comment]
PR opened to cover the text colour, the other piece is actually a feature cahnge in: https://github.com/FlowFuse/node-red-dashboard/pull/1166

The them you have should be switched to a "Row Height" of "Comortable (36px)" (default is 48px). We had some inconsistencies between Grid/Fixed layouts that were addressed there, and the "Comfortable" layout will give you what you had before for Fixed layouts.

**Comment by colinl** [comment]
Unfortunately changing the row height to Comfortable did not appear to change anything.  I restarted node-red and cleared the browser cache.  Did you check it with my flow?

**Comment by joepavitt** [comment]
Yes, otherwise I wouldn't have recommended it 😁 

How many themes do you have locally, are you sure you're changing the correct one?

**Comment by joepavitt** [comment]
## Default

<img width="1006" alt="Screenshot 2024-08-20 at 14 04 05" src="https://github.com/user-attachments/assets/7494dd2f-13fe-49c2-bf64-cad7d625f057">

## Comfortable

<img width="1018" alt="Screenshot 2024-08-20 at 14 04 30" src="https://github.com/user-attachments/assets/a7a2697d-73ee-4c51-a1da-2836c5ba2458">

## Compact:

<img width="1059" alt="Screenshot 2024-08-20 at 14 02 46" src="https://github.com/user-attachments/assets/5aedcb82-f580-450d-9138-e27b7906cb38">

**Comment by colinl** [comment]
For both of them I created new user directories and then ran node red for that directory.  Then I installed just the dashboard and configured the text nodes.

Did you try it on 1.14.0? The differences between the image you posted is not as great as I see between the two versions.

**Comment by joepavitt** [comment]
So the height is working as I'd expect, but it does look like we have an issue with the card's width in Fixed views. No matter what I change the group width to, they're always rendering at `320px` wide - which accordingly to the git history, is a line of code I put in 14 months ago - so need to dig into what's changed 🤔

**Comment by colinl** [comment]
I don't think this should have been closed by #1218, there are still unresolved issues.

**Comment by joepavitt** [comment]
Correct - looks like GH auto-closed it because I'd mentioned it

**Comment by joepavitt** [comment]
Just tracking this back, the changes came in here: https://github.com/FlowFuse/node-red-dashboard/pull/1166/files#r1725334033

We had an inconsistency that 1 unit of size in Grid/Notebook/Tabs was `48px` but in `Fixed` it was `45px` - this cahnge made them consistent, but as a result, meant that the cells are now wider in "Fixed"

The solution here will be to change the width of the elements/groups to be slightly narrower.

**Comment by joepavitt** [comment]
Whilst the above is true, there is still an underlying bug introduced whereby the group width is not taken into account at all when rendering the groups. Have the fix, not sure how it's changed though, as the line I need to remove is from 14 months ago

**Comment by colinl** [comment]
I still don't think this is right.  This flow has three groups of width 3.  The first has three text nodes of size 1x1 and the other groups the text nodes are 3x1.  In 1.14.0 this looks like this, which is correct I think

![image](https://github.com/user-attachments/assets/7d845e01-66a3-414b-9c01-6bb938d54baa)


In the latest it looks like

![image](https://github.com/user-attachments/assets/90f42c2f-62aa-4c0f-83a8-9699628e83cd)

```
[{"id":"dcdf6d0bcedf02e5","type":"ui-text","z":"371f5f719cb5e2ab","group":"a5e220219816243f","order":1,"width":"1","height":"1","name":"","label":"text_1.1","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":140,"y":160,"wires":[]},{"id":"5b24e7fe449f6810","type":"ui-text","z":"371f5f719cb5e2ab","group":"a5e220219816243f","order":3,"width":"1","height":"1","name":"","label":"text_1.3","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":460,"y":160,"wires":[]},{"id":"40af9b6e24de780e","type":"ui-text","z":"371f5f719cb5e2ab","group":"a5e220219816243f","order":2,"width":"1","height":"1","name":"","label":"text_1.2","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":300,"y":160,"wires":[]},{"id":"cbf83482e17c2b4b","type":"ui-text","z":"371f5f719cb5e2ab","group":"e0f34190373ab7df","order":1,"width":"3","height":"1","name":"","label":"text_2.1","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":720,"y":160,"wires":[]},{"id":"09307acb332b44cf","type":"ui-text","z":"371f5f719cb5e2ab","group":"e0f34190373ab7df","order":3,"width":"3","height":"1","name":"","label":"text_3.3","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":720,"y":280,"wires":[]},{"id":"ed10149bb6492858","type":"ui-text","z":"371f5f719cb5e2ab","group":"e0f34190373ab7df","order":2,"width":"3","height":"1","name":"","label":"text_2.2","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":720,"y":220,"wires":[]},{"id":"b50c4c40032edab9","type":"ui-text","z":"371f5f719cb5e2ab","group":"f65b9a76255edbd0","order":1,"width":"3","height":"1","name":"","label":"text_3.1","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":940,"y":160,"wires":[]},{"id":"60cc180687fb0928","type":"ui-text","z":"371f5f719cb5e2ab","group":"f65b9a76255edbd0","order":3,"width":"3","height":"1","name":"","label":"text_3.3","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":940,"y":280,"wires":[]},{"id":"c218ab2fed9e6fce","type":"ui-text","z":"371f5f719cb5e2ab","group":"f65b9a76255edbd0","order":2,"width":"3","height":"1","name":"","label":"text_2.2","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":940,"y":220,"wires":[]},{"id":"a5e220219816243f","type":"ui-group","name":"Group1","page":"4527544ddbb29343","width":"3","height":"1","order":1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"e0f34190373ab7df","type":"ui-group","name":"Group 2","page":"4527544ddbb29343","width":"3","height":"1","order":2,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"f65b9a76255edbd0","type":"ui-group","name":"Group 3","page":"4527544ddbb29343","width":"3","height":"1","order":3,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"4527544ddbb29343","type":"ui-page","name":"1.14.0","ui":"4df7e5236771d85d","path":"/page1","icon":"home","layout":"flex","theme":"30b58d6104e752ec","order":1,"className":"","visible":"true","disabled":"false"},{"id":"4df7e5236771d85d","type":"ui-base","name":"My Dashboard","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-notification","ui-control"],"showPathInSidebar":false,"showPageTitle":true,"navigationStyle":"default","titleBarStyle":"default"},{"id":"30b58d6104e752ec","type":"ui-theme","name":"Default Theme","colors":{"surface":"#ffffff","primary":"#0094CE","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"},"sizes":{"pagePadding":"12px","groupGap":"12px","groupBorderRadius":"4px","widgetGap":"12px"}}]
```

**Comment by joepavitt** [comment]
In 1.14.0 and below we actually had a bug where all groups were a fixed size, no matter what group size you set, which is what you've seen. I did fix that, but it appears there may be more at play:

<img width="538" alt="Screenshot 2024-08-22 at 10 15 20" src="https://github.com/user-attachments/assets/0dac5ca0-f05f-47ce-bcb1-dc1483c11dd6">

<img width="516" alt="Screenshot 2024-08-22 at 10 15 32" src="https://github.com/user-attachments/assets/18846447-40a6-404a-a605-a3aba0a4a92b">

@gayanSandamal can you investigate this as a priority please?

**Comment by colinl** [comment]
It seems to be OK in Grid mode, it is just Fixed where I see the problem.

**Comment by colinl** [comment]
> In 1.14.0 and below we actually had a bug where all groups were a fixed size, no matter what group size you set

In 1.14.0 if I set group three to 6 wide I see this, which appears to contradict the suggestion that they were all the same size, unless I misunderstand what you mean.

![image](https://github.com/user-attachments/assets/715ba9d1-0bb1-4622-bbb8-d3fc40f31f89)

**Comment by joepavitt** [comment]
In which case, something changed between `1.14.0` and the `main` branch I was testing last night to force them all to the same size instead then 🤔 

Thanks for the investigation - I've asked @gayanSandamal to take a look at this

**Comment by gayanSandamal** [comment]
> In which case, something changed between `1.14.0` and the `main` branch I was testing last night to force them all to the same size instead then 🤔 
> 
> 
> 
> Thanks for the investigation - I've asked @gayanSandamal to take a look at this

@joepavitt I approved this PR because the expected behavior was there

https://github.com/FlowFuse/node-red-dashboard/pull/1223#pullrequestreview-2251479329

**Comment by joepavitt** [comment]
I know, but as Colin has pointed out, and I can see with his shared flow, something is still broken as those groups should all be the same size, and tou can see in my shared screenshot that the unit sizing is inconsistent

**Comment by gayanSandamal** [comment]
> In 1.14.0 and below we actually had a bug where all groups were a fixed size, no matter what group size you set, which is what you've seen. I did fix that, but it appears there may be more at play:
> 
> <img alt="Screenshot 2024-08-22 at 10 15 20" width="538" src="https://private-user-images.githubusercontent.com/99246719/360366418-0dac5ca0-f05f-47ce-bcb1-dc1483c11dd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjcwOTgsIm5iZiI6MTcyNDMyNjc5OCwicGF0aCI6Ii85OTI0NjcxOS8zNjAzNjY0MTgtMGRhYzVjYTAtZjA1Zi00N2NlLWJjYjEtZGMxNDgzYzExZGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDExMzk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMWE0OWJkN2Y1ZjU2MmI5OWUzN2E3MDBiYjA1NDgwMjEzNjE2Y2M2MmU4YzYyMjE3YTQ4NjM4YmFjNGMwNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VjXzrhZ3bcjW5LLbBqTlXjkDVGKL6LS9hQ6ddBzq97Q"> <img alt="Screenshot 2024-08-22 at 10 15 32" width="516" src="https://private-user-images.githubusercontent.com/99246719/360366480-18846447-40a6-404a-a605-a3aba0a4a92b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjcwOTgsIm5iZiI6MTcyNDMyNjc5OCwicGF0aCI6Ii85OTI0NjcxOS8zNjAzNjY0ODAtMTg4NDY0NDctNDBhNi00MDRhLWE2MDUtYTNhYmEwYTRhOTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDExMzk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NmM1NGY5M2FmNWRlZTNlYTBjZDljNTU0YjdlYTc4ZTIwMjYxZjAzNjBkOTY0MDk3NDc0YzNhMTAwNDM4ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TQAo1IOKynshhijB-y70KQYQTRCavLBu-38rWW-m0c0">
> @gayanSandamal can you investigate this as a priority please?

@joepavitt Sorry, I didn't see this message as I was checking the thread on my phone. I'm currently looking into this with the flow given by @colinl https://github.com/FlowFuse/node-red-dashboard/issues/1215#issuecomment-2304152615

**Comment by colinl** [comment]
Great.  Looking good now.
